name: Build Solun App

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19.6.0

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build